# apply: kubectl apply -f k8s-rws.yaml
# check: kubectl get all
# check on service: curl http://localhost:30000/api/v1/helloworld

apiVersion: v1
kind: Service
metadata:
  name: rws-service
spec:
  type: NodePort
  selector:
    app: rws
  ports:
      # targetPort is Pod/container's port. port is where other pods (in same cluster) connect to.
    - port: 80
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rws-deployment
  labels:
    app: rws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rws
  template:
    metadata:
      labels:
        app: rws
    spec:
      containers:
      - name: rws
        image: djayap/rustwebservice:latest
        ports:
        - containerPort: 8080